[env]
term = "xterm-256color"

[window]
decorations = "Transparent"
dynamic_padding = false
opacity = 0.95
startup_mode = "Maximized"

[window.padding]
x = 20
y = 25

[font]
size = 18.0

[font.normal]
family = 'Hack Nerd Font Mono'
#family = 'Iosevka Nerd Font Mono'

[general]
live_config_reload = true
import = [
    # "~/.config/alacritty/themes/kanagawa_wave.toml"
    "~/.config/alacritty/themes/catppuccin.toml"
]

